services:

  app:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-sidecar:4317
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc 
      OTEL_RESOURCE_ATTRIBUTES: service.name=custom_app

  otel-sidecar:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-sidecar-conf.yaml:/etc/otelcol/config.yaml

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-conf.yaml:/etc/otelcol/config.yaml


